// src/Publisher/Stubs/Client/Svelte/Pages/Dashboard.svelte
<script>
    import AppLayout from '../Layouts/AppLayout.svelte';
</script>

<svelte:head>
    <title>Dashboard</title>
</svelte:head>

<AppLayout>
    <h2 slot="header" class="font-semibold text-xl text-gray-800 leading-tight">
        Dashboard
    </h2>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">You're logged in!</div>
            </div>
        </div>
    </div>
</AppLayout>

// src/Publisher/Stubs/Client/React/Pages/Dashboard.tsx
import { Head } from '@inertiajs/react';
import AppLayout from '../Layouts/AppLayout';

export default function Dashboard() {
    return (
        <AppLayout
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Dashboard</h2>}
        >
            <Head title="Dashboard" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">You're logged in!</div>
                    </div>
                </div>
            </div>
        </AppLayout>
    );
}
