// src/Publisher/Stubs/Client/Svelte/WithAuth/pages/auth/email-2fa-verify.svelte
<script>
    import { Head, useForm, page } from '@inertiajs/svelte';
    import GuestLayout from '../../layouts/guest-layout.svelte';

    let form = useForm({
        token: ''
    });

    function submit() {
        $form.post('/auth/a/verify');
    }
</script>

<svelte:head>
    <title>Verify Code</title>
</svelte:head>

<GuestLayout>
    <div class="mb-8">
        <h1 class="text-2xl font-bold text-base-content">Verify Identity</h1>
        <p class="text-base-content/70 mt-1">Enter the 6-digit code sent to your email.</p>
    </div>

    {#if $page.props.flash?.error}
        <div class="mb-6 alert alert-error text-sm py-3 px-4 font-medium">
            {$page.props.flash.error}
        </div>
    {/if}

    <form on:submit|preventDefault={submit} class="space-y-5">
        <div>
            <label for="token" class="block text-sm font-semibold text-base-content/85 mb-1">Verification Code</label>
            <input
                id="token"
                type="text"
                bind:value={$form.token}
                class="input input-bordered w-full text-center text-2xl tracking-widest font-black"
                placeholder="000000"
                required
                autofocus
                autocomplete="one-time-code"
            />
            {#if $form.errors.token}
                <div class="mt-2 text-sm text-error font-medium">{$form.errors.token}</div>
            {/if}
        </div>

        <div class="pt-2">
            <button
                type="submit"
                disabled={$form.processing}
                class="btn btn-primary w-full shadow-md"
            >
                {#if $form.processing}
                    <span class="loading loading-spinner"></span>
                {:else}
                    Verify & Sign In
                {/if}
            </button>
        </div>
    </form>
</GuestLayout>

// src/Publisher/Stubs/Client/React/WithAuth/pages/auth/email-2fa-verify.tsx
import { Head, useForm, usePage } from '@inertiajs/react';
import GuestLayout from '../../layouts/guest-layout';
import { FormEvent } from 'react';

export default function Email2FAVerify() {
    const { props } = usePage();
    const flash = props.flash as any;

    const { data, setData, post, processing, errors } = useForm({
        token: '',
    });

    const submit = (e: FormEvent) => {
        e.preventDefault();
        post('/auth/a/verify');
    };

    return (
        <GuestLayout>
            <Head title="Verify Code" />

            <div className="mb-8">
                <h1 className="text-2xl font-bold text-base-content">Verify Identity</h1>
                <p className="text-base-content/70 mt-1">Enter the 6-digit code sent to your email.</p>
            </div>

            {flash?.error && (
                <div className="mb-6 alert alert-error text-sm py-3 px-4 font-medium">
                    {flash.error}
                </div>
            )}

            <form onSubmit={submit} className="space-y-5">
                <div>
                    <label htmlFor="token" className="block text-sm font-semibold text-base-content/85 mb-1">Verification Code</label>
                    <input
                        id="token"
                        type="text"
                        value={data.token}
                        onChange={(e) => setData('token', e.target.value)}
                        className="input input-bordered w-full text-center text-2xl tracking-widest font-black"
                        placeholder="000000"
                        required
                        autoFocus
                        autoComplete="one-time-code"
                    />
                    {errors.token && (
                        <div className="mt-2 text-sm text-error font-medium">{errors.token}</div>
                    )}
                </div>

                <div className="pt-2">
                    <button
                        type="submit"
                        disabled={processing}
                        className="btn btn-primary w-full shadow-md"
                    >
                        {processing ? <span className="loading loading-spinner"></span> : 'Verify & Sign In'}
                    </button>
                </div>
            </form>
        </GuestLayout>
    );
}
