// src/Publisher/Stubs/Client/Svelte/WithAuth/pages/auth/magic-link-message.svelte
<script>
    import { Head, Link, page } from '@inertiajs/svelte';
    import GuestLayout from '../../layouts/guest-layout.svelte';
</script>

<svelte:head>
    <title>Magic Link Sent</title>
</svelte:head>

<GuestLayout>
    {#if $page.props.flash?.message}
        <div class="mb-6 alert alert-success text-sm py-3 px-4 font-medium">
            {$page.props.flash.message}
        </div>
    {/if}

    <div class="mb-6 text-sm text-base-content/75 leading-relaxed">
        We have emailed you a magic link. Please check your inbox and click the link to log in.
    </div>

    <div class="mt-6 text-center">
        <Link href="/login" class="font-bold text-primary hover:text-secondary transition-colors">
            Back to Log in
        </Link>
    </div>
</GuestLayout>

// src/Publisher/Stubs/Client/React/WithAuth/pages/auth/magic-link-message.tsx
import { Head, Link, usePage } from '@inertiajs/react';
import GuestLayout from '../../layouts/guest-layout';

export default function MagicLinkMessage() {
    const { props } = usePage();
    const flash = props.flash as any;

    return (
        <GuestLayout>
            <Head title="Magic Link Sent" />

            {flash?.message && (
                <div className="mb-6 alert alert-success text-sm py-3 px-4 font-medium">
                    {flash.message}
                </div>
            )}

            <div className="mb-6 text-sm text-base-content/75 leading-relaxed">
                We have emailed you a magic link. Please check your inbox and click the link to log in.
            </div>

            <div className="mt-6 text-center">
                <Link href="/login" className="font-bold text-primary hover:text-secondary transition-colors">
                    Back to Log in
                </Link>
            </div>
        </GuestLayout>
    );
}
