// src/Publisher/Stubs/Client/React/Pages/Auth/MagicLinkMessage.tsx
import { Head, Link } from '@inertiajs/react';
import GuestLayout from '../../Layouts/GuestLayout';

export default function MagicLinkMessage() {
    return (
        <GuestLayout>
            <Head title="Magic Link Sent" />

            <div className="mb-4 text-sm text-gray-600">
                Check your email! We've sent you a magic link to log in.
            </div>

            <div className="mt-4 flex items-center justify-between">
                <Link
                    href="/login"
                    className="underline text-sm text-gray-600 hover:text-gray-900 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                    Back to login
                </Link>
            </div>
        </GuestLayout>
    );
}

// src/Publisher/Stubs/Client/Vue/Pages/Auth/MagicLinkMessage.vue
<script setup>
import { Head, Link, usePage } from '@inertiajs/vue3'
import GuestLayout from '../../Layouts/GuestLayout.vue'
import { computed } from 'vue'

const page = usePage()
const flash = computed(() => page.props.flash)
</script>

<template>
    <GuestLayout>
        <Head title="Magic Link Sent" />

        <div v-if="flash.message" class="mb-4 font-medium text-sm text-green-600">{{ flash.message }}</div>

        <div class="mb-4 text-sm text-gray-600">
            We have emailed you a magic link. Please check your inbox and click the link to log in.
        </div>

        <div class="mt-6 text-center">
            <Link href="/login" class="font-medium text-indigo-600 hover:text-indigo-500">
                Back to Log in
            </Link>
        </div>
    </GuestLayout>
</template>
