// src/Publisher/Stubs/Client/React/Pages/Auth/Register.tsx
import { Head, Link, useForm } from '@inertiajs/react';
import GuestLayout from '../../Layouts/GuestLayout';
import { FormEventHandler } from 'react';

export default function Register() {
    const { data, setData, post, processing, errors } = useForm({
        username: '',
        email: '',
        password: '',
        password_confirm: '',
    });

    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post('/register');
    };

    return (
        <GuestLayout>
            <Head title="Register" />

            <form onSubmit={submit}>
                <div>
                    <label htmlFor="username" className="block text-sm font-medium text-gray-700">Username</label>
                    <input
                        id="username"
                        type="text"
                        name="username"
                        value={data.username}
                        className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                        autoComplete="username"
                        onChange={(e) => setData('username', e.target.value)}
                        required
                    />
                    {errors.username && <div className="mt-2 text-sm text-red-600">{errors.username}</div>}
                </div>

                <div className="mt-4">
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700">Email</label>
                    <input
                        id="email"
                        type="email"
                        name="email"
                        value={data.email}
                        className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                        autoComplete="email"
                        onChange={(e) => setData('email', e.target.value)}
                        required
                    />
                    {errors.email && <div className="mt-2 text-sm text-red-600">{errors.email}</div>}
                </div>

                <div className="mt-4">
                    <label htmlFor="password" className="block text-sm font-medium text-gray-700">Password</label>
                    <input
                        id="password"
                        type="password"
                        name="password"
                        value={data.password}
                        className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                        autoComplete="new-password"
                        onChange={(e) => setData('password', e.target.value)}
                        required
                    />
                    {errors.password && <div className="mt-2 text-sm text-red-600">{errors.password}</div>}
                </div>

                <div className="mt-4">
                    <label htmlFor="password_confirm" className="block text-sm font-medium text-gray-700">Confirm Password</label>
                    <input
                        id="password_confirm"
                        type="password"
                        name="password_confirm"
                        value={data.password_confirm}
                        className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                        autoComplete="new-password"
                        onChange={(e) => setData('password_confirm', e.target.value)}
                        required
                    />
                    {errors.password_confirm && <div className="mt-2 text-sm text-red-600">{errors.password_confirm}</div>}
                </div>

                <div className="mt-6">
                    <button
                        type="submit"
                        className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
                        disabled={processing}
                    >
                        Register
                    </button>
                </div>

                <p className="mt-4 text-center text-sm text-gray-600">
                    Already have an account?{' '}
                    <Link href="/login" className="font-medium text-indigo-600 hover:text-indigo-500">
                        Log in
                    </Link>
                </p>
            </form>
        </GuestLayout>
    );
}

// src/Publisher/Stubs/Client/Svelte/Pages/Auth/Register.svelte
<script>
    import { inertia, useForm } from "@inertiajs/svelte";
    import GuestLayout from "../../Layouts/GuestLayout.svelte";

    let form = useForm({
        username: "",
        email: "",
        password: "",
        password_confirm: "",
    });

    function submit() {
        $form.post("/register");
    }
</script>

<svelte:head>
    <title>Register</title>
</svelte:head>

<GuestLayout>
    <form on:submit|preventDefault={submit}>
        <div>
            <label
                for="username"
                class="block text-sm font-medium text-gray-700">Username</label
            >
            <input
                id="username"
                type="text"
                bind:value={$form.username}
                class="mt-1 block w-full p-2 border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                required
                autocomplete="username"
            />
            {#if $form.errors.username}
                <div class="mt-2 text-sm text-red-600">
                    {$form.errors.username}
                </div>
            {/if}
        </div>

        <div class="mt-4">
            <label for="email" class="block text-sm font-medium text-gray-700"
                >Email</label
            >
            <input
                id="email"
                type="email"
                bind:value={$form.email}
                class="mt-1 block w-full p-2 border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                required
                autocomplete="email"
            />
            {#if $form.errors.email}
                <div class="mt-2 text-sm text-red-600">
                    {$form.errors.email}
                </div>
            {/if}
        </div>

        <div class="mt-4">
            <label
                for="password"
                class="block text-sm font-medium text-gray-700">Password</label
            >
            <input
                id="password"
                type="password"
                bind:value={$form.password}
                class="mt-1 block w-full p-2 border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                required
                autocomplete="new-password"
            />
            {#if $form.errors.password}
                <div class="mt-2 text-sm text-red-600">
                    {$form.errors.password}
                </div>
            {/if}
        </div>

        <div class="mt-4">
            <label
                for="password_confirm"
                class="block text-sm font-medium text-gray-700"
                >Confirm Password</label
            >
            <input
                id="password_confirm"
                type="password"
                bind:value={$form.password_confirm}
                class="mt-1 block w-full p-2 border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                required
                autocomplete="new-password"
            />
            {#if $form.errors.password_confirm}
                <div class="mt-2 text-sm text-red-600">
                    {$form.errors.password_confirm}
                </div>
            {/if}
        </div>

        <div class="mt-6">
            <button
                type="submit"
                disabled={$form.processing}
                class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 {$form.processing
                    ? 'opacity-50'
                    : ''}"
            >
                Register
            </button>
        </div>

        <p class="mt-4 text-center text-sm text-gray-600">
            Already have an account?
            <a
                href="/login"
                use:inertia
                class="font-medium text-indigo-600 hover:text-indigo-500"
            >
                Log in
            </a>
        </p>
    </form>
</GuestLayout>
