// src/Publisher/Stubs/Client/Vue/Pages/Auth/Email2FAVerify.vue
<script setup>
import { Head, useForm, usePage } from '@inertiajs/vue3'
import GuestLayout from '../../Layouts/GuestLayout.vue'
import { computed } from 'vue'

const page = usePage()
const flash = computed(() => page.props.flash)

const form = useForm({
    token: ''
})

const submit = () => {
    form.post('/auth/a/verify')
}
</script>

<template>
    <GuestLayout>
        <Head title="Verify Code" />

        <div class="mb-8">
            <h1 class="text-2xl font-bold text-slate-900">Verify Identity</h1>
            <p class="text-slate-500 mt-1">Enter the 6-digit code sent to your email.</p>
        </div>

        <div v-if="flash.error" class="mb-6 p-4 rounded-xl bg-red-50 text-red-700 text-sm font-medium border border-red-100">
            {{ flash.error }}
        </div>

        <form @submit.prevent="submit" class="space-y-5">
            <div>
                <label for="token" class="block text-sm font-semibold text-slate-700 mb-1">Verification Code</label>
                <input
                    id="token"
                    type="text"
                    v-model="form.token"
                    class="jengo-input text-center text-2xl letter-spacing-widest font-black"
                    placeholder="000000"
                    required
                    autofocus
                    autocomplete="one-time-code"
                />
                <div v-if="form.errors.token" class="mt-2 text-sm text-red-600 font-medium">{{ form.errors.token }}</div>
            </div>

            <div class="pt-2">
                <button
                    type="submit"
                    :class="{ 'opacity-50': form.processing }"
                    :disabled="form.processing"
                    class="jengo-button w-full"
                >
                    Verify & Sign In
                </button>
            </div>
        </form>
    </GuestLayout>
</template>

// src/Publisher/Stubs/Client/Svelte/WithAuth/pages/auth/email-2fa-verify.svelte
<script>
    import { Head, useForm, page } from '@inertiajs/svelte';
    import GuestLayout from '../../layouts/guest-layout.svelte';

    let form = useForm({
        token: ''
    });

    function submit() {
        $form.post('/auth/a/verify');
    }
</script>

<svelte:head>
    <title>Verify Code</title>
</svelte:head>

<GuestLayout>
    <div class="mb-8">
        <h1 class="text-2xl font-bold text-base-content">Verify Identity</h1>
        <p class="text-base-content/70 mt-1">Enter the 6-digit code sent to your email.</p>
    </div>

    {#if $page.props.flash?.error}
        <div class="mb-6 alert alert-error text-sm py-3 px-4 font-medium">
            {$page.props.flash.error}
        </div>
    {/if}

    <form on:submit|preventDefault={submit} class="space-y-5">
        <div>
            <label for="token" class="block text-sm font-semibold text-base-content/85 mb-1">Verification Code</label>
            <input
                id="token"
                type="text"
                bind:value={$form.token}
                class="input input-bordered w-full text-center text-2xl tracking-widest font-black"
                placeholder="000000"
                required
                autofocus
                autocomplete="one-time-code"
            />
            {#if $form.errors.token}
                <div class="mt-2 text-sm text-error font-medium">{$form.errors.token}</div>
            {/if}
        </div>

        <div class="pt-2">
            <button
                type="submit"
                disabled={$form.processing}
                class="btn btn-primary w-full shadow-md"
            >
                {#if $form.processing}
                    <span class="loading loading-spinner"></span>
                {:else}
                    Verify & Sign In
                {/if}
            </button>
        </div>
    </form>
</GuestLayout>
