// src/Publisher/Stubs/Client/Vue/WithAuth/layouts/guest-layout.vue
<script setup>
import { Link } from '@inertiajs/vue3'
</script>

<template>
    <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-base-200 text-base-content relative overflow-hidden">
        <!-- Background decorative elements -->
        <div class="absolute -top-24 -left-24 w-96 h-96 bg-primary/10 rounded-full blur-3xl"></div>
        <div class="absolute -bottom-24 -right-24 w-96 h-96 bg-secondary/10 rounded-full blur-3xl"></div>
        
        <div class="z-10">
            <Link href="/" class="flex items-center gap-2 group">
                <div class="w-12 h-12 bg-gradient-to-tr from-primary to-secondary rounded-xl flex items-center justify-center shadow-lg shadow-primary/20 group-hover:scale-110 transition-transform duration-300">
                    <span class="text-2xl font-black text-white italic">J</span>
                </div>
                <span class="text-3xl font-black tracking-tighter text-base-content">JENGO</span>
            </Link>
        </div>

        <div class="w-full sm:max-w-md mt-8 px-8 py-10 card bg-base-100 shadow-xl border border-base-300/50 z-10 mx-4">
            <slot />
        </div>
        
        <div class="mt-8 text-base-content/50 text-sm z-10">
            &copy; {{ new Date().getFullYear() }} Jengo Framework. Built for speed.
        </div>
    </div>
</template>

// src/Publisher/Stubs/Client/React/WithAuth/layouts/guest-layout.tsx
import { Link } from '@inertiajs/react';
import { PropsWithChildren } from 'react';

export default function GuestLayout({ children }: PropsWithChildren) {
    return (
        <div className="min-h-screen flex flex-col justify-center items-center py-12 px-4 bg-base-200 font-sans antialiased text-base-content relative overflow-hidden">
            {/* Background decorative elements */}
            <div className="absolute -top-48 -left-48 w-96 h-96 bg-primary/10 rounded-full blur-3xl"></div>
            <div className="absolute bottom-0 right-0 w-96 h-96 bg-secondary/10 rounded-full blur-3xl"></div>

            <div className="w-full max-w-md z-10">
                <div className="flex justify-center mb-6">
                    <Link href="/" className="flex items-center gap-3 group">
                        <div className="w-12 h-12 bg-gradient-to-tr from-primary to-secondary rounded-xl flex items-center justify-center shadow-lg shadow-primary/20 group-hover:scale-105 transition-transform">
                            <span className="text-2xl font-black text-white italic">J</span>
                        </div>
                        <span className="text-3xl font-black tracking-tighter text-base-content">JENGO</span>
                    </Link>
                </div>

                <div className="card bg-base-100 border border-base-300/50 p-8 shadow-xl">
                    {children}
                </div>
            </div>
        </div>
    );
}
